name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  formz: ^0.8.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/

